import React from 'react';
import { getScanReport } from '../api';

export default function ReportExport({ url }) {
  const handleExport = async (format) => {
    try {
      const report = await getScanReport(url);

      let content, mimeType, filename;

      if (format === 'json') {
        content = JSON.stringify(report, null, 2);
        mimeType = 'application/json';
        filename = `securescan_report_${new Date().toISOString().slice(0, 10)}.json`;
      } else {
        // Generate text report
        const lines = [
          '='.repeat(60),
          '  SecureScan — Vulnerability Assessment Report',
          '='.repeat(60),
          `  Target URL  : ${report.target}`,
          `  Scan Date   : ${report.scan_date}`,
          `  Score        : ${report.score}/100 (Grade: ${report.grade})`,
          `  Tests Passed : ${report.tests_passed}/${report.tests_total}`,
          '='.repeat(60),
          '',
          '── Risk Summary ──',
          `  Total Issues : ${report.risk_summary?.total || 0}`,
          `  High         : ${report.risk_summary?.high || 0}`,
          `  Medium       : ${report.risk_summary?.medium || 0}`,
          `  Low          : ${report.risk_summary?.low || 0}`,
          '',
          '── OWASP Top 10 Results ──',
        ];

        (report.owasp_results || []).forEach(r => {
          const icon = r.status === 'pass' ? '✓ PASS' : '✗ FAIL';
          lines.push(`  [${r.owasp_id}] ${r.owasp_name} — ${icon}`);
          lines.push(`         Severity   : ${r.severity}`);
          lines.push(`         Description: ${r.description}`);
          if (r.status === 'fail' && r.recommendation) {
            lines.push(`         Fix        : ${r.recommendation}`);
          }
          lines.push('');
        });

        if (report.recommendations?.length) {
          lines.push('── Recommendations ──');
          report.recommendations.forEach((rec, i) => {
            lines.push(`  ${i + 1}. ${rec}`);
          });
        }

        lines.push('', '='.repeat(60));
        lines.push('  Report generated by SecureScan v2.0');
        lines.push('='.repeat(60));

        content = lines.join('\n');
        mimeType = 'text/plain';
        filename = `securescan_report_${new Date().toISOString().slice(0, 10)}.txt`;
      }

      const blob = new Blob([content], { type: mimeType });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = filename;
      link.click();
      URL.revokeObjectURL(link.href);
    } catch (err) {
      console.error('Failed to export report:', err);
    }
  };

  return (
    <div className="flex flex-wrap gap-3">
      <button
        onClick={() => handleExport('json')}
        className="flex items-center gap-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition-all hover:shadow-indigo-500/40"
      >
        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        Export JSON Report
      </button>
      <button
        onClick={() => handleExport('txt')}
        className="flex items-center gap-2 rounded-xl bg-slate-700 hover:bg-slate-600 px-5 py-2.5 text-sm font-semibold text-slate-200 border border-white/10 transition-all"
      >
        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        Export Text Report
      </button>
    </div>
  );
}
